version: "3.8"
services:
    
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                MODE: ${MODE}
        image: melearn
        volumes:
            - melearn-public-uploads:/code/packages/server/public/uploads
            - melearn-uploads:/code/packages/server/uploads
        ports:
            - "3333:3333"
volumes:
    melearn-public-uploads:
    melearn-uploads: