version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:delegated
      - /workspace/node_modules
      - /workspace/packages/server/node_modules
      - /workspace/packages/client/node_modules

    command: /bin/sh -c "while sleep 1000; do :; done"
 
